# Generated by Django 2.2 on 2020-04-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(null=True, upload_to='', verbose_name='Attach a picture'),
        ),
    ]
