# Generated by Django 2.2 on 2020-04-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20200403_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(null=True, upload_to='post-images', verbose_name='Attach a picture'),
        ),
    ]
